### ISSUE TITLE
serialize_bytes returns Error::UnsupportedType

### ISSUE THREAD

**Issue by dfaust** [alexcrichton/toml-rs#150]
Since version 0.3, `ser::Serializer::serialize_bytes` returns `Error::UnsupportedType`, which makes it impossible to serialize various types from `sodiumoxide`.
Is this a bug in `toml-rs` or does the `sodiumoxide` implementation need to be changed?

**Comment by alexcrichton** [comment]
Yeah I initially changed this because I thought `serialize_bytes` was intended for "large blobs of bytes", but TOML Isn't great at serializing raw bytes (e.g. it's just a textual array). Is this turning out to be a problem, though? I certainly wouldn't mind switching it to just serialize a list of numbers instead.

**Comment by dfaust** [comment]
Yes, `toml-rs` used to serialize "bytes" to a list of 8 bit integers. Deserialization actually still works, so reading something like `key = [72, 165, 63, ...]` can be deserialized into a `sodiumoxide::crypto::secretbox::Key`.
