### ISSUE TITLE
Add a preserve_order feature like in serde-json

### ISSUE THREAD

**Issue by Keats** [alexcrichton/toml-rs#232]
See https://github.com/serde-rs/json/blob/master/Cargo.toml#L39

For a crate, I'd like to iterate on a table in the order of the TOML input, would it make sense/be possible to add that to toml-rs as well?

**Comment by peterhuene** [comment]
This would be lovely to have implemented and thanks for the PR @Keats.

For me, in lieu of stable `cargo new` templating feature, I'm editing `Cargo.toml` programmatically and it's ordering `dependencies` before `package`.  Since I'm literally just modifying the manifest to add a few dependencies, I might just append the lines without parsing the file (of course, that makes it sensitive to changes in `cargo new` output, but hopefully templating is coming sooner than later as this is just a stopgap).

**Comment by ehuss** [comment]
`preserve_order` has been added in #278.
