### ISSUE TITLE
Empty copyright in apache license

### ISSUE THREAD

**Issue by qwerty541** [alexcrichton/toml-rs#401]
https://github.com/alexcrichton/toml-rs/blob/master/LICENSE-APACHE#L189

With empty copyright it is just template, isn`t it?

**Comment by ehuss** [comment]
I believe it is intentional (though not required to be included per the definition of "License").  The full text of the license is from [here](https://www.apache.org/licenses/LICENSE-2.0.txt). It instructs the person on the receiving end of the license how to apply the license correctly to their derivative work.  It can be removed, or kept, I don't think it matters.

**Comment by dtolnay** [comment]
Yeah I think this is correct as is. Not every project that the person receiving this license will apply it to will have the same copyright year / owner.
