### ISSUE TITLE
Serialization error

### ISSUE THREAD

**Issue by 0xdeafbeef** [alexcrichton/toml-rs#402]
```
#[derive(Deserialize, Debug, Clone, Serialize)]
struct OutputProps {
    save_to_file: bool,
    filename: Option<String>,
    pretty_format: bool,
    show_progress: bool,
    keep_incremental_data: Option<bool>,
}

#[derive(Deserialize, Debug, Clone, Serialize)]
struct Config {
    threads: usize,
    command: String,
    output: OutputProps,
    timeout: u32,
}
```
Failes to serialize such structure, but serializes it, if i change order of fields.
```
struct Config {
    threads: usize,
    command: String,
    timeout: u32,
    output: OutputProps
}
```
Error repeasts with:
 `toml 0.5.6`  and  `serde 1.0.104`.

**Comment by ehuss** [comment]
As described in the [`ValueAfterTable`](https://docs.rs/toml/0.5.6/toml/ser/enum.Error.html#variant.ValueAfterTable) error, it is not possible to have values after tables, you'll need to rearrange it so that the tables are at the end of the definition. There currently isn't a way to control the use of inline tables (#265).
