### ISSUE TITLE
Let parse return a Result

### ISSUE THREAD

**Issue by thijsc** [alexcrichton/toml-rs#69]
It seems like it would be much more convenient if `Parser.parse` returned a result that includes the error if there's a failure. Any specific reason why it's an option? Would you be open to a pull to change this?

**Comment by alexcrichton** [comment]
This was currently done because the errors returned are actually a vector of errors, stored in the `errors` field of the parser. At the time I felt somewhat uneasy returning `Result<Table, Vec<Error>>`, but I totally agree that it'd probably be best now to just return a `Result` instead of returning an `Option`. 

Unfortunately that's a breaking change to make now and I have a feeling if I were going to make other breaking changes I'd also rewrite the parser interface and perhaps add a tokenizer on top first. (maybe even separate the parse and validation steps). For now I'd like to hold off on breaking toml-rs just yet, but this is certainly the first thing I'd consider with a version bump!

**Comment by thijsc** [comment]
Thanks for the explanation. Makes a lot of sense.

**Comment by waynr** [comment]
@alexcrichton yo, I have been trying out this library the past couple weeks and am also interested in having `Parser.parse` return a `Result` that contains some kind of `Error`.  It looks like #78 contains more details about the interface you have in mind so I'll finish commenting there.

**Comment by alexcrichton** [comment]
I think I've fixed this when rewriting for serde 0.9: https://github.com/alexcrichton/toml-rs/pull/137

**Comment by alexcrichton** [comment]
Fixed in #137
