### ISSUE TITLE
Error serialising unit-like `enum`s

### ISSUE THREAD

**Issue by mseri** [alexcrichton/toml-rs#71]
If the `enum` is unit-like it is not serialized by toml. At least I keep getting error.

If I try the same with rustc-serialize `json` it is serialized without complaints.

A very-non-minimal test example is:

```
extern crate rustc_serialize;
extern crate toml;

use toml::{Encoder, Value};
use rustc_serialize::Encodable;

#[derive(RustcEncodable)]
enum Yolo { One, Two, Three }

#[derive(RustcEncodable)]
struct MyStruct { foo: isize, bar: String, baz: Yolo }

fn main() {
  let my_struct = MyStruct { foo: 4, bar: "hello!".to_string(), baz: Yolo::One };

  let mut e = Encoder::new();
  my_struct.encode(&mut e).unwrap();

  assert_eq!(e.toml.get(&"foo".to_string()), Some(&Value::Integer(4)))
}
```

This fails to run with 
```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: NoValue', ../src/libcore/result.rs:731.
````

**Comment by alexcrichton** [comment]
Yeah unfortunately this crate doesn't "just work" with all possible Rust values, due to the way that it handles `enum`s. This crate's auto-interpretation of deriving/encoding enums is that each enum is tried in turn when deserializing, returning the first that works (and when serializing it basically pretends the layer of indirection of the enum doesn't exist.

This means that if you want something like this to work you'll want to implement `Rustc{Encodable,Decodable}` yourself to e.g. convert the enum to a string on both ends.

Thanks for the report though!
