### ISSUE TITLE
impl fmt::Display for ParserError should include a source location

### ISSUE THREAD

**Issue by gwillen** [alexcrichton/toml-rs#77]
... or there should be some obvious way to display a ParserError that includes display of a source location.

**Comment by alexcrichton** [comment]
Yeah this has turned out to be a bit of an unfortunate original decision. The fields of the error are all public so they can't be changed backwards-compatibly, and the line/column information are stored in a side table rather than in the error itself.

Overall I've not been too happy with how the error interface for parsing turned out, and I'd be more than willing to just completely overhaul it! I'd also like to improve the perfornace of the parser, however, so I may hold off on the changes for now at least.

**Comment by gwillen** [comment]
Ahh, so just to make sure I'm understanding this correctly -- it would be pointless to display the fields from the error struct, because (although present) they are always unused, and the real info is stored elsewhere? That makes sense. Feel free to close this bug or make it track whatever you need in terms of surfacing this info somewhere useful. Thanks!

**Comment by alexcrichton** [comment]
Oh no this is indeed a legitimate bug, but the fields shouldn't necessarily be discarded they just need to be translated. The `lo` and `hi` fields can be passed back to the parser's `to_linecol` method to get a line/column of the original TOML document, but the file name or perhaps other source of the information would have be stored on the side elsewhere.

I'm fine leaving this open though as it's something I'd like to take into account if the parser is ever rewritten.

**Comment by alexcrichton** [comment]
I think I've fixed this for the serde 0.9 rewrite: https://github.com/alexcrichton/toml-rs/pull/137

**Comment by alexcrichton** [comment]
Fixed in #137
